### ISSUE TITLE
Design "Events" Page

### ISSUE THREAD

**Issue by IEC-NMIMS** [IEC-NMIMS/iec-website#11]
### **Tasks to be Performed:**
___
- Create the following page, assume required components:
![Events](https://github.com/IEC-NMIMS/iec-website/assets/154611742/21454a69-a818-4604-9a4c-8a1549df2a17)

**Comment by Sushanth-Tambe-2102** [comment]
https://github.com/IEC-NMIMS/iec-website/pull/18
