### ISSUE TITLE
Add "Hover Effect" to "Events" Page

### ISSUE THREAD

**Issue by IEC-NMIMS** [IEC-NMIMS/iec-website#16]
### **Tasks to be Performed:**
___
- Create the following page, assume required components:
![Hover on Events](https://github.com/IEC-NMIMS/iec-website/assets/154611742/26ac3e0f-a9db-47cb-944b-3efa51536456)

**Comment by YashKorla** [comment]
https://github.com/IEC-NMIMS/iec-website/pull/29
