### ISSUE TITLE
Design "On-Click Modal" for "Events" Page

### ISSUE THREAD

**Issue by IEC-NMIMS** [IEC-NMIMS/iec-website#17]
### **Tasks to be Performed:**
___
- Create the following page, assume required components:
![Modal for Events](https://github.com/IEC-NMIMS/iec-website/assets/154611742/806f29c0-4d0c-4a2e-8907-cdea1074807b)

**Comment by YashKorla** [comment]
https://github.com/IEC-NMIMS/iec-website/pull/29
