### ISSUE TITLE
Design "Inceptio" Page

### ISSUE THREAD

**Issue by IEC-NMIMS** [IEC-NMIMS/iec-website#36]
### **Tasks to be Performed**
___
- Create the following page, assume required components:
![Inceptio Page](https://github.com/IEC-NMIMS/iec-website/assets/154611742/8ab15eae-c0a1-41f3-969f-7d183e861fea)

**Comment by YashKorla** [comment]
https://github.com/IEC-NMIMS/iec-website/pull/37
